### ISSUE TITLE
ModuleNotFoundError: No module named 'LLM_location'

### ISSUE THREAD

**Issue by mosoriob** [In-For-Disaster-Analytics/sites-and-stories-nlp#22]
Seems to caused by da0ec405cfa2ed2f78a83e09230d880161040fb1

![image](https://github.com/In-For-Disaster-Analytics/sites-and-stories-nlp/assets/2365990/6e3d3d2e-5c9c-4436-9dcc-8c7baa0d1613)

**Comment by wmobley** [comment]
I changed the Package organization, to improve readability and modularity. Forgot to fix the notebook.
